import { loadStripe } from "@stripe/stripe-js";
import { useRef, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  const paymentFormRef = useRef();
  const [inProgress, setInProgress] = useState(false)

  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      setInProgress(true)
      const data = new FormData(paymentFormRef.current);
      const payload = {
        email: data.get('email'),
        amount: data.get('amount'),
        walletAddr: data.get("walletAddr")
      };
      const response = await fetch(`/api/checkout?email=${payload.email}&amount=${payload.amount}&walletAddr=${payload.walletAddr}`)
      const { session} = await response.json();
      const stripe = await loadStripe(process.env.NEXT_PUBLIC_STRIPE_KEY);
      stripe.redirectToCheckout({ sessionId: session.id })

      setInProgress(false)
    } catch(err) {
      setInProgress(false)
      console.log({ err })
    }


  }

  return (
    <div className={styles.container}>
      <Head>
        <title>DINT - Payments Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          DINT payment test app
        </h1>

        <p className={styles.description}>
          Get started by checking{' '}
          <code className={styles.code}>pages/index.js</code>
          and docs
        </p>

        <form ref={paymentFormRef} onSubmit={handleSubmit}>
          <input
            name="walletAddr"
            required
            placeholder='Type wallet address'
            style={{display: "block", width: "100%", padding: "5px", fontSize: "16px", marginBottom: "5px"}}
          />
          <input
            name="email"
            type="email"
            required
            placeholder='Type your e-mail'
            style={{display: "block", width: "100%", padding: "5px", fontSize: "16px", marginBottom: "5px"}}
          />
          <input
            required
            type="number"
            name="amount"
            min={1}
            max={10000}
            placeholder='Value in USD'
            style={{display: "block", width: "100%", padding: "5px", fontSize: "16px"}}
          />
          <button
            style={{marginTop: "5px", width: "100%", padding: "5px", fontSize: "16px"}}
            type="submit"
            disabled={inProgress}
          >
            {inProgress && "Please wait..."}
            {!inProgress && "Start payment"}
          </button>
        </form>
      </main>
    </div>
  )
}
